services:
  apache:
    image: php:8.3-apache
    container_name: spt-apache
    volumes:
      - ./src:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    command: >
      bash -c "
        docker-php-ext-install mysqli pdo pdo_mysql &&
        a2enmod rewrite &&
        apache2-foreground
      "

  db:
    image: mysql:9.4.0
    container_name: spt-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 124358
      MYSQL_DATABASE: spt_db
      MYSQL_USER: patric
      MYSQL_PASSWORD: patric
    ports:
      - "3318:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
